logging:
  level:
    root: INFO
    me:
      marcelberger: DEBUG

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/homepage
    username: root
    password: root

homepage:
  media:
    basePath: V:\homepage
  security:
    corsOrigins: |
      http://localhost:4200